### ISSUE TITLE
"2016 JavaScript Rising Stars" in Japanese

### ISSUE THREAD

**Issue by michaelrambeau** [michaelrambeau/risingstars2016#9]
Hello @azukiwasher @meltedice @vanx2,
I'd like to translate in Japanese 🇯🇵  the content inside the folder `i18n`, in the branch `feature/multilingual`.

There are 2 kinds of files to translate:

* markdown files: 
  * `i18n/introduction/ja.md`: the introduction
  * `i18n/categories/*/ja.md`: the 10 blocks of text (comments about the graphs)
  * `i18n/conclusion/ja.md`: the conclusion
* yaml files for String messages (short content): `i18n/messages/ja.yaml`

Inside the markdown files, `{}` is a place holder used to generate automatically links to the Github projects.
For example:

* before: `aaaa {react} bbbb`
* after `aaaa [React](https://facebook.github.io/react/) bbbb`

You can translate by updating the files directly from Github web UI, you don't have to run the project locally.

You are **free**, you can write something different from the English version!

Thank you very much!

**Comment by michaelrambeau** [comment]
Hello @meltedice @azukiwasher @vanx2 

FYI I set up an **automatic** deployment process with Netlify.

**Every** `commit` to `feature/multilingual` branch triggers a build process and you can see the result here:

http://risingstars2016.netlify.com/ja/ (this is a temporary URL, kind of `staging` environment)

**Comment by azkwsr** [comment]
@meltedice @vanx2 which categories would you like to translate?

**Comment by azkwsr** [comment]
@meltedice @vanx2 
I would like to translate the following categories (with check box) if you don’t mind... 

- [x] Introduction
- [x] Conclusion

---

- [x] 1. (ja) Most Popular Projects in 2016
2. (ja) Front-end Frameworks
3. (ja) Node.js Frameworks
4. (ja) React Boilerplates
- [x] 5. (ja) Mobile
6. (ja) Compilers
- [x] 7. (ja) Build Tools
- [x] 8. (ja) Testing Frameworks
- [x] 9. (ja) IDE
- [x] 10. (ja) Static Site Generators

---

- [x] messages/ja.yaml

**Comment by vanx2** [comment]
will do No.3 at first!

**Comment by meltedice** [comment]
First, I'll do 2 Front-end Frameworks!

> 2. (ja) Front-end Frameworks
https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/framework/ja.md

**Comment by meltedice** [comment]
Index

1. (ja) Most Popular Projects in 2016 (Overview)
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/all/ja.md
2. (ja) Front-end Frameworks
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/framework/ja.md
3. (ja) Node.js Frameworks
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/nodejs-framework/ja.md
4. (ja) React Boilerplates
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/react-template/ja.md
5. (ja) Mobile
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/mobile/ja.md
6. (ja) Compilers
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/compiler/ja.md
7. (ja) Build Tools
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/build/ja.md
8. (ja) Testing Frameworks
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/test-framework/ja.md
9. (ja) IDE
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/ide/ja.md
10. (ja) Static Site Generators
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/ssg/ja.md

```
1. (ja) Most Popular Projects in 2016 (Overview)
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/all/ja.md
2. (ja) Front-end Frameworks
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/framework/ja.md
3. (ja) Node.js Frameworks
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/nodejs-framework/ja.md
4. (ja) React Boilerplates
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/react-template/ja.md
5. (ja) Mobile
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/mobile/ja.md
6. (ja) Compilers
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/compiler/ja.md
7. (ja) Build Tools
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/build/ja.md
8. (ja) Testing Frameworks
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/test-framework/ja.md
9. (ja) IDE
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/ide/ja.md
10. (ja) Static Site Generators
    * https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/categories/ssg/ja.md
```

**Comment by michaelrambeau** [comment]
@azukiwasher Thank you very much, the introduction, the conclusion, the sections number 1 ("Most popular projects"), 8 ("Testing") and 9 ("SSG") look great!

@meltedice @vanx2 よろしくお願いします 😄 

If you don't understand well what I said in the English version, you can make it simpler, shorter, no problem!

I will add the "credits" at the end of the page: 

> Japanese translation by @azukiwasher, @meltedice and @vanx2

**Comment by azkwsr** [comment]
I have just finished 5 ("Mobile").

**Comment by michaelrambeau** [comment]
@azukiwasher Thank you very much, you are my hero, I will study Japanese by reading what you wrote!

Could you translate the Strings in the `yaml` file ?
https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/i18n/messages/ja.yaml

The `description` is very important because this is what Google displays in Search results.
It's what Slack displays when you share a link too.
Thank you again!

**Comment by meltedice** [comment]
Super fast!

**Comment by azkwsr** [comment]
just finished 9 ("IDE").

@michaelrambeau 

> Could you translate the Strings in the yaml file ?

Yes, sir!

**Comment by azkwsr** [comment]
got work done: `messages/ja.yaml`

**Comment by azkwsr** [comment]
@michaelrambeau 
i did not find the word `Conclusion` under `i18n`. Where can i find to translate it? 

![image](https://cloud.githubusercontent.com/assets/442462/22287834/b6a1bba2-e337-11e6-9b51-b5de8841f838.png)

**Comment by vanx2** [comment]
No.3 is almost done, currently confirming.

next will be No.6 Compilers!

**Comment by meltedice** [comment]
I'll push `2. Front-end Frameworks` then translate `4. (ja) React Boilerplates` .

**Comment by michaelrambeau** [comment]
@azukiwasher Thank you again, I have just added 2 keys to `ja.yaml`:

```yaml
conclusion: "(ja) Conclusion"

social:
  text: "(ja) Check the JavaScript landscape in 2016"  
```

@vanx2 Thank you for the node.js frameworks, it's good!

@meltedice Thank you in advance, do not hesitate to ask if you need explanation!

頑張ってください！

**Comment by meltedice** [comment]
I finally translated `2. Front-end Frameworks` and `4. (ja) React Boilerplates` .
(I don't know why but I started to watch recorded TV program 鉄腕DASH! (Tetsuwan DASH!))
(before finish translation...)

We need to check our translated Japanse each other.
I also need to check mentioned projects github pages, to know their background.

**Comment by michaelrambeau** [comment]
@meltedice Thank you very much Ice-san! 

But did you sleep enough ? 😴  💤  ?

**Comment by michaelrambeau** [comment]
Hello @azukiwasher @meltedice @vanx2 
We are close to the goal!

### Todo

@vanx2 will do the `Compilers` section.
So there will be only section left: `Build` (ビルドツール)
Don't worry if you're busy, you worked **a lot** for the project, we can leave it in English and I will add a button "EDIT" that will open the file in Github (so that anyone can make a Pull Request and translate it).

Tonight I will merge into master and publish the page if you are OK.

And tonight we can start the promotion plan (see #11 ). It's exciting ❗️ 

### Credits

I have added your names in the footer page:

![image](https://cloud.githubusercontent.com/assets/5546996/22313789/b9263cb2-e3a1-11e6-99c6-2080343da664.png)

Can I display your Github avatars ?
I can add a short bio too, if your want.

You can fix your name and your URL in this file: https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/config.toml

**Comment by azkwsr** [comment]
@michaelrambeau 

i will soon get work done with `7. Build`.

Github avatars and bio, no problem with me. it's welcome.

**Comment by michaelrambeau** [comment]
@azukiwasher Thank you for thr building tools (ビルドツール) !

I will add the avatars tonight.

**Comment by michaelrambeau** [comment]
Thank you very much @vanx2 now it's 100% translated in Japanese 🎉  !

Let's think about the promotion now, let's go to #11

**Comment by vanx2** [comment]
`No.6 Compilers` is done!

mmm... but I should improve my works...

@michaelrambeau it's my honor! please add me :)

**Comment by meltedice** [comment]
Yes, you can use my GitHub avator.
And better to add GitHub link?

>>>
Can I display your Github avatars ?
I can add a short bio too, if your want.

You can fix your name and your URL in this file: https://github.com/michaelrambeau/risingstars2016/blob/feature/multilingual/config.toml

**Comment by michaelrambeau** [comment]
OK Thank you very much @meltedice , I will do that tonight.

And then I will merge everything and deploy the production web site.

Stay tuned!

**Comment by michaelrambeau** [comment]
@azukiwasher , @meltedice , @vanx2 Let me know if the bio and the avatar are correct, thank you!

![image](https://cloud.githubusercontent.com/assets/5546996/22333221/426ae20e-e418-11e6-84c0-939e107af5c2.png)
